DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE USER(
USER_ID 			varchar(36) NOT NULL,
USER_NAME 		varchar(80) NOT NULL,
USER_EMAIL 		varchar(80) NOT NULL,
PASSWORD 		varchar(30) NOT NULL,
CREATE_TS		DATETIME	NOT NULL,
LAST_CHANGE_TS	DATETIME NOT NULL,
USER_TYPE		CHAR(8)	NOT NULL,
PRIMARY KEY(USER_ID),
CONSTRAINT "EMAIL_UNIQUE" UNIQUE (USER_EMAIL)
);

CREATE TABLE ACCOUNT(
ACCNT_NBR 		INTEGER NOT NULL,
ACCNT_BAL 		float NOT NULL,
ACCNT_CURR 		varchar(10) NOT NULL,
USER_ID 			varchar(36) NOT NULL,
CREATE_TS		DATETIME	 NOT NULL,
LAST_CHANGE_TS	DATETIME NOT NULL,
PRIMARY KEY(ACCNT_NBR)
);
ALTER TABLE ACCOUNT ADD CONSTRAINT "USER" FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

CREATE TABLE TRANSACTION(
TRANS_ID 		VARCHAR(36) NOT NULL,
TRANS_AMT 		float NOT NULL,
TOTAL_BAL		float NOT NULL,
TRANS_CURR 		VARCHAR(10) NOT NULL,
ACCNT_NBR 		INTEGER NOT NULL,
TRANS_TS 		DATETIME NOT NULL,
TRANS_STATUS 	VARCHAR(10) NOT NULL,
TRANS_COMMENT	VARCHAR(200),
PRIMARY KEY(TRANS_ID, ACCNT_NBR)
);
ALTER TABLE TRANSACTION ADD CONSTRAINT "TO_ACCOUNT" FOREIGN KEY (ACCNT_NBR) REFERENCES ACCOUNT(ACCNT_NBR);

